spring:
  profiles:
    active:
      - dev
  main:
    web-application-type: servlet

server:
  port: 8080

curse-forge:
  base-url: ${CURSE_FORGE_API_URL:https://api.curseforge.com}
  api-key: ${CURSE_FORGE_API_KEY:}
  indexes-path: ${CURSE_FORGE_INDEXES_PATH:}
  mods-path: ${CURSE_FORGE_MODS_PATH:}
  ignore-size-check: false
  ignore-hash-check: false
